[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Otter"
authors = [{name = "Bloxster", email = "9mors3@zoho.com"}]
dynamic = ["version", "description"]
